#! /usr/bin/bash

PacConfig="/etc/pacman.conf"
MkinitcpioConfig="/etc/mkinitcpio.conf"
InstallUser="${SUDO_USER:-$USER}"
InstallHome="$(getent passwd "$InstallUser" | cut -d: -f6)"
InstallGroup="$(id -gn "$InstallUser" 2>/dev/null)"
InstallUid="$(id -u "$InstallUser" 2>/dev/null)"
if [ -z "$InstallHome" ]; then
	InstallHome="$HOME"
fi
if [ -z "$InstallGroup" ]; then
	InstallGroup="$InstallUser"
fi
if [ -z "$InstallUid" ]; then
	InstallUid="$(id -u)"
fi

Title='\e[34m'
Success='\e[32m'
Install='\e[33m'
Fail='\e[31m'
END='\e[0m'

handleInstall() {
	local pkg="$1"
	if ! paru -Qq | grep -qx "$pkg"; then
		echo -e "$pkg ${Fail}not${END} found, ${Install}installing${END}."
		paru -S --noconfirm "$pkg"
	else	
		echo -e "$pkg" ${Success}installed${END}.
	fi
}

runAsInstallUser() {
	if [ "$(id -u)" -eq 0 ] && [ "$InstallUser" != "root" ]; then
		sudo -u "$InstallUser" env HOME="$InstallHome" XDG_RUNTIME_DIR="/run/user/$InstallUid" "$@"
	else
		"$@"
	fi
}

waitForHyprlandExit() {
	local pid="$1"
	local attempts=0

	while kill -0 "$pid" >/dev/null 2>&1 && [ "$attempts" -lt 30 ]; do
		sleep 1
		attempts=$((attempts + 1))
	done

	if kill -0 "$pid" >/dev/null 2>&1; then
		echo "Hyprland did not exit after hyprshutdown; stopping first-run session."
		kill "$pid" >/dev/null 2>&1 || true
	fi

	wait "$pid" 2>/dev/null || true
}

configureNvidiaInitramfs() {
	local current_modules
	local modules_text
	local module
	local nvidia_modules=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)

	echo "Configure NVIDIA modules in mkinitcpio"
	sudo touch "$MkinitcpioConfig"
	current_modules="$(grep -E '^\s*MODULES=' "$MkinitcpioConfig" | head -n 1)"

	if [ -n "$current_modules" ]; then
		modules_text="$(printf '%s\n' "$current_modules" | sed -E 's/^[[:space:]]*MODULES=\(([^)]*)\).*/\1/')"
	else
		modules_text=""
	fi

	for module in "${nvidia_modules[@]}"; do
		if ! printf ' %s ' "$modules_text" | grep -q " $module "; then
			modules_text="$modules_text $module"
		fi
	done

	modules_text="$(printf '%s\n' "$modules_text" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; s/[[:space:]]+/ /g')"
	if grep -qE '^\s*MODULES=' "$MkinitcpioConfig"; then
		sudo sed -i -E "0,/^[[:space:]]*MODULES=/{s|^[[:space:]]*MODULES=.*|MODULES=($modules_text)|}" "$MkinitcpioConfig"
	else
		echo "MODULES=($modules_text)" | sudo tee -a "$MkinitcpioConfig" >/dev/null
	fi

	sudo mkinitcpio -P
}

ensureHyprLine() {
	local line="$1"
	local config="$2"

	if ! grep -qxF "$line" "$config"; then
		printf '%s\n' "$line" >> "$config"
	fi
}

configureHyprlandConfig() {
	local config="$InstallHome/.config/hypr/hyprland.conf"

	echo "Configure Hyprland"
	mkdir -p "$InstallHome/.config/hypr"
	if [ ! -f "$config" ]; then
		cp /usr/share/hypr/hyprland.conf "$config"
	fi

	sed -i -E 's/^([[:space:]]*)autogenerated[[:space:]]*=/\1# autogenerated =/' "$config"
	sed -i -E '/^[[:space:]]*general[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*gaps_in[[:space:]]*=.*/    gaps_in = 2/' "$config"
	sed -i -E '/^[[:space:]]*general[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*gaps_out[[:space:]]*=.*/    gaps_out = 5/' "$config"
	sed -i -E '/^[[:space:]]*general[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*border_size[[:space:]]*=.*/    border_size = 1/' "$config"
	sed -i -E '/^[[:space:]]*decoration[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*rounding[[:space:]]*=.*/    rounding = 0/' "$config"
	sed -i -E '/^[[:space:]]*decoration[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*rounding_power[[:space:]]*=.*/    rounding_power = 0/' "$config"
	sed -i -E '/^[[:space:]]*shadow[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*enabled[[:space:]]*=.*/        enabled = false/' "$config"
	sed -i -E '/^[[:space:]]*blur[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*enabled[[:space:]]*=.*/        enabled = false/' "$config"
	sed -i -E '/^[[:space:]]*animations[[:space:]]*\{/,/^[[:space:]]*\}/ s/^[[:space:]]*enabled[[:space:]]*=.*/    enabled = false/' "$config"

	if grep -qE '^\s*\$terminal\s*=' "$config"; then
		sed -i -E 's|^\s*\$terminal\s*=.*|$terminal = foot|' "$config"
	else
		ensureHyprLine '$terminal = foot' "$config"
	fi

	if grep -qE '^\s*\$fileManager\s*=' "$config"; then
		sed -i -E 's|^\s*\$fileManager\s*=.*|$fileManager = pcmanfm-qt|' "$config"
	else
		ensureHyprLine '$fileManager = pcmanfm-qt' "$config"
	fi

	if grep -qE '^\s*\$menu\s*=' "$config"; then
		sed -i -E 's|^\s*\$menu\s*=.*|$menu = fuzzel|' "$config"
	else
		ensureHyprLine '$menu = fuzzel' "$config"
	fi

	ensureHyprLine 'env = LIBVA_DRIVER_NAME,nvidia' "$config"
	ensureHyprLine 'env = __GLX_VENDOR_LIBRARY_NAME,nvidia' "$config"
	ensureHyprLine 'env = ELECTRON_OZONE_PLATFORM_HINT,auto' "$config"
	ensureHyprLine 'env = NVD_BACKEND,direct' "$config"

	ensureHyprLine 'exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP' "$config"
	ensureHyprLine 'exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP' "$config"
	ensureHyprLine 'exec-once = systemctl --user start hyprpolkitagent' "$config"
	ensureHyprLine 'exec-once = systemctl --user start xdg-desktop-portal xdg-desktop-portal-hyprland' "$config"
	ensureHyprLine 'exec-once = dunst' "$config"
	ensureHyprLine 'exec-once = hyprpaper' "$config"
	ensureHyprLine 'exec-once = ashell' "$config"
	ensureHyprLine 'exec-once = udiskie --tray' "$config"
	ensureHyprLine 'exec-once = wl-paste --type text --watch cliphist store' "$config"
	ensureHyprLine 'exec-once = wl-paste --type image --watch cliphist store' "$config"
	ensureHyprLine "exec-once = sh -c 'command -v monique >/dev/null 2>&1 && monique'" "$config"

	ensureHyprLine 'bind = $mainMod SHIFT, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy' "$config"
	ensureHyprLine 'bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit' "$config"
	ensureHyprLine 'bind = $mainMod, E, exec, $fileManager' "$config"
	ensureHyprLine 'bind = $mainMod, R, exec, $menu' "$config"

	if [ "$InstallUser" != "root" ]; then
		sudo chown "$InstallUser:$InstallGroup" "$config"
	fi
}

echo -e "${Title}-----ZERTHS_ARCH_INSTALLER-----${END}"
echo "When prompted, please provide password and/or select Y/y"
echo -e "System ${Install}installation${END} will begin..."

echo "Configuring Pacman."
if ! grep -qE '^\s*Color\b' "$PacConfig"; then
echo "Enabling Color in Pacman."
	sudo sed -i 's/^\s*#\s*Color\b/Color/' "$PacConfig"
	if ! grep -qE '^\s*Color\b' "$PacConfig"; then
		echo "Color" | sudo tee -a "$PacConfig" >/dev/null
	fi
fi


echo -e "${Title}Updating System.${END}"
sudo pacman -Syu
echo "Adding development packages."
sudo pacman -S --needed base-devel
echo "Acquiring Git"
if ! command -v git >/dev/null 2>&1; then
	echo -e "Git ${Fail}not${END} found, ${Install}installing${END}."
	sudo pacman -S git
else
	echo -e "Git ${Success}installed${END}."
fi
git config --global user.email "drkainaan@icloud.com"
git config --global user.name "TheZerth"

echo -e "#${Title}Acquiring Paru${END}"
if [ ! -x /usr/bin/paru ]; then
	echo -e "Paru ${Fail}not${END} found, ${Install}installing${END}."
	cd
	git clone "https://aur.archlinux.org/paru.git"
	cd paru
	makepkg -si
else
	echo -e "Paru ${Success}installed${END}."
fi
handleInstall bat


echo -e "${Title}Acquiring Base Packages${END}"
handleInstall linux-zen-headers
handleInstall amd-ucode
handleInstall tuned
handleInstall sof-firmware
handleInstall linux-firmware-marvell
handleInstall man-db
handleInstall man-pages
handleInstall texinfo
handleInstall nano
handleInstall neovim
handleInstall fish
handleInstall python
handleInstall networkmanager
handleInstall bluez
handleInstall bluez-utils
handleInstall cmake
handleInstall ninja
handleInstall clang

echo -e "${Title}Configuring Terminal${END}"
cd "$InstallHome"
if [ ! -d "$InstallHome/proggyfonts" ]; then
	git clone "https://www.github.com/bluescan/proggyfonts.git" "$InstallHome/proggyfonts"
else
	echo -e "ProggyFonts ${Success}installed${END}."
fi
handleInstall terminus-font
handleInstall fontconfig
sudo setfont ter-714n
sudo touch /etc/vconsole.conf
if sudo grep -qE '^\s*FONT=' /etc/vconsole.conf; then
	sudo sed -i 's/^\s*FONT=.*/FONT=ter-714n/' /etc/vconsole.conf
else
	echo "FONT=ter-714n" | sudo tee -a /etc/vconsole.conf >/dev/null
fi

echo -e "${Title}Configuring Audio${END}"
handleInstall pipewire 
handleInstall lib32-pipewire
handleInstall pipewire-docs
handleInstall wireplumber
handleInstall pipewire-audio
handleInstall pipewire-alsa
handleInstall pipewire-pulse
handleInstall pipewire-jack 
handleInstall lib32-pipewire-jack
handleInstall alsa-utils
systemctl --user enable pipewire wireplumber pipewire-pulse

echo -e "${Title}Configuring Video${END}"
handleInstall dkms
handleInstall nvidia-open-dkms 
handleInstall nvidia-utils 
handleInstall lib32-nvidia-utils 
handleInstall nvidia-settings
handleInstall gamemode
handleInstall lib32-gamemode
handleInstall vulkan-tools
configureNvidiaInitramfs

echo -e "${Title}Setup Desktop${END}"
handleInstall hyprland 
handleInstall aquamarine 
handleInstall hyprlang 
handleInstall hyprcursor 
handleInstall hyprutils 
handleInstall hyprgraphics
handleInstall hyprtoolkit
handleInstall hyprland-guiutils 
handleInstall hyprwayland-scanner
handleInstall hyprpaper
handleInstall xdg-desktop-portal
handleInstall xdg-desktop-portal-hyprland
handleInstall hyprpolkitagent
handleInstall hyprpwcenter
handleInstall hyprshutdown
handleInstall mako
handleInstall dunst
handleInstall libnotify
handleInstall qt5-wayland
handleInstall qt6-wayland
handleInstall ashell
handleInstall fuzzel
handleInstall wl-clipboard
handleInstall cliphist
handleInstall udiskie
handleInstall pcmanfm-qt
handleInstall monique
echo "Start Hyprland once to generate configs"
if [ -n "$WAYLAND_DISPLAY" ] || [ -n "$DISPLAY" ]; then
	echo "Skipping Hyprland first-run because a graphical session is already active."
elif [ "$InstallUser" = "root" ]; then
	echo "Skipping Hyprland first-run because no non-root install user was detected."
elif ! command -v start-hyprland >/dev/null 2>&1; then
	echo "start-hyprland not found; skipping Hyprland first-run."
else
	HyprlandLog="$InstallHome/.cache/zerth-hyprland-first-run.log"
	mkdir -p "$InstallHome/.cache"
	touch "$HyprlandLog"
	sudo chown "$InstallUser:$InstallGroup" "$InstallHome/.cache" "$HyprlandLog"

	runAsInstallUser start-hyprland -- > "$HyprlandLog" 2>&1 &
	HyprlandPid=$!
	sleep 10

	if runAsInstallUser hyprctl --instance 0 dispatch exec hyprshutdown >/dev/null 2>&1; then
		waitForHyprlandExit "$HyprlandPid"
	else
		echo "hyprshutdown did not start; asking Hyprland to exit directly."
		runAsInstallUser hyprctl --instance 0 dispatch exit >/dev/null 2>&1 || true
		waitForHyprlandExit "$HyprlandPid"
	fi
fi
configureHyprlandConfig

echo -e "${Title}Install Applications${END}"
handleInstall foot
handleInstall vesktop
handleInstall steam
handleInstall gamescope
handleInstall xorg-xwayland
handleInstall protontricks
handleInstall wine
handleInstall winetricks
handleInstall freecad
handleInstall firefox
handleInstall visual-studio-code-bin
handleInstall jetbrains-toolbox
handleInstall btop

echo -e "${Title}Configuring Arch${END}"
echo "Enable SSD TRIM"
sudo systemctl enable fstrim.timer
echo "Set GPU MAX Power Mode"
sudo nvidia-smi -pm 1
nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=1"
echo "Enable TuneD"
sudo systemctl enable tuned.service
sudo systemctl start tuned.service
sudo tuned-adm profile throughput-performance
echo "Enable NetworkManager"
sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service
echo "Enable Bluetooth"
sudo systemctl enable bluetooth.service
sudo systemctl start bluetooth.service
echo "Set user shell to Fish"
if [ -n "$InstallUser" ] && [ "$InstallUser" != "root" ]; then
	if ! grep -qx "/usr/bin/fish" /etc/shells; then
		echo "/usr/bin/fish" | sudo tee -a /etc/shells >/dev/null
	fi
	sudo chsh -s /usr/bin/fish "$InstallUser"
else
	echo "Skipping shell change because no non-root install user was detected."
fi
echo "Configure Foot font"
ProggyFont="$InstallHome/proggyfonts/ProggyOriginal/ProggyClean.ttf"
FootConfig="$InstallHome/.config/foot/foot.ini"
FootFont="ProggyClean"
if [ -f "$ProggyFont" ]; then
	mkdir -p "$InstallHome/.local/share/fonts/proggyfonts" "$InstallHome/.config/foot"
	ln -sf "$ProggyFont" "$InstallHome/.local/share/fonts/proggyfonts/ProggyClean.ttf"
	fc-cache -f "$InstallHome/.local/share/fonts/proggyfonts"
	if command -v fc-scan >/dev/null 2>&1; then
		ScannedFootFont="$(fc-scan --format '%{family[0]}' "$ProggyFont" 2>/dev/null)"
		if [ -n "$ScannedFootFont" ]; then
			FootFont="$ScannedFootFont"
		fi
	fi
	if [ -f "$FootConfig" ]; then
		if grep -qE '^\s*font=' "$FootConfig"; then
			sed -i "s|^\s*font=.*|font=$FootFont:pixelsize=14|" "$FootConfig"
		elif grep -qE '^\s*\[main\]' "$FootConfig"; then
			sed -i "/^\s*\[main\]/a font=$FootFont:pixelsize=14" "$FootConfig"
		else
			printf "\n[main]\nfont=%s:pixelsize=14\n" "$FootFont" >> "$FootConfig"
		fi
	else
		printf "[main]\nfont=%s:pixelsize=14\n" "$FootFont" > "$FootConfig"
	fi
	if [ "$InstallUser" != "root" ]; then
		sudo chown -R "$InstallUser:$InstallGroup" "$InstallHome/.config/foot" "$InstallHome/.local/share/fonts/proggyfonts"
	fi
else
	echo "ProggyClean.ttf not found at $ProggyFont; skipping Foot font configuration."
fi
echo -e "${Title}Copying SSH Keys${END}"
cd
mkdir USB
mount /dev/sda1 ./USB
cp -r ./USB/.ssh/* ~/.ssh/
umount /dev/sda1

sudo reboot
